runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /admin/.*
  login: admin
  script: main.app

- url: /
  static_files: static_dart_build/index.html
  upload: static_dart_build/index\.html

- url: /(.*)$
  static_files: static_dart_build/\1
  upload: static_dart_build/.*$

- url: /.*
  static_dir: static_dart_build

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest